// EVE v2 — Real-feeling places with photo hero, friend-voice descriptions.

// Each place has a `category` that drives the fallback when there's no
// `photo`. Categories map to: a representative image (food/drink, never
// the place itself), a tinted color, and a typographic glyph.
window.EVE_CATEGORIES = {
  dive:      { label: 'Dive bar',       tint: '#7A3B1F', accent: '#F4A05A',
               photo: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=1200&q=80&auto=format&fit=crop',
               glyph: 'a beer on a wooden bar' },
  pub:       { label: 'Pub',            tint: '#3D2818', accent: '#D4A574',
               photo: 'https://images.unsplash.com/photo-1571767454098-246b94fbcf70?w=1200&q=80&auto=format&fit=crop',
               glyph: 'a pint of stout' },
  cocktail:  { label: 'Cocktail bar',   tint: '#2B1B2F', accent: '#E8B4D0',
               photo: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=1200&q=80&auto=format&fit=crop',
               glyph: 'a coupe with a twist' },
  coffee:    { label: 'Coffee',         tint: '#3A2818', accent: '#C89F6F',
               photo: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200&q=80&auto=format&fit=crop',
               glyph: 'an espresso pull' },
  diner:     { label: 'Diner',          tint: '#7A2118', accent: '#F2C078',
               photo: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1200&q=80&auto=format&fit=crop',
               glyph: 'a stack of pancakes' },
  punk:      { label: 'Punk bar',       tint: '#1A1A1F', accent: '#F09060',
               photo: 'https://images.unsplash.com/photo-1538488881038-e252a119ace7?w=1200&q=80&auto=format&fit=crop',
               glyph: 'neon over a pool table' },
};

const EVE_PLACES = [
  {
    id: 1, name: "Sophie's", kind: 'Dive bar', category: 'dive',
    street: '507 E 5th St', cross: 'btwn Aves A & B',
    hours: 'Open till 4am', open: true, vibe: 'Loud · Cash only · No frills',
    photo: 'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=1200&q=80&auto=format&fit=crop',
    photoCredit: 'Submitted by @ev_regular',
    pitch: "The jukebox is the whole personality. Go on a Tuesday — it gets weird in the best way, and your $4 PBR will somehow taste like the meaning of life.",
    perfect: "you want to talk for hours and not look at a menu",
    tags: ['Dive', 'Cheap drinks', 'Cash only', 'Open late'],
    insider: "Order the well whiskey, sit in the back booth, don't bother with the bathroom situation.",
    crowd: 'Locals, NYU grads who never left',
    distance: '4 min walk', closesIn: '7h 19m',
    signal: { kind: 'happy', label: 'Happy hour ends at 8', urgent: true, eta: '22 min' },
    crowdLevel: 'Light', priceTier: '$',
  },
  {
    id: 2, name: "Mona's", kind: 'Irish pub', category: 'pub',
    street: '224 Avenue B', cross: 'at E 14th',
    hours: 'Open till 4am', open: true, vibe: 'Live music · Warm · No phones',
    photo: null,
    pitch: "Monday night trad session at 11 sharp. The fiddler is your new favorite person and the pint is poured like it matters — because it does.",
    perfect: "you want a Monday that doesn't feel like a Monday",
    tags: ['Live music', 'Trad session', 'Pints', 'Open late'],
    insider: "Don't talk during a tune. Tip the bartender in cash, even if you tab.",
    crowd: 'Musicians, regulars, the occasional wandering poet',
    distance: '8 min walk', closesIn: '7h 19m',
    signal: { kind: 'music', label: 'Trad session starts 11pm', urgent: false, eta: '3h 19m' },
    crowdLevel: 'Filling up', priceTier: '$$',
  },
  {
    id: 3, name: 'Abraço', kind: 'Espresso bar', category: 'coffee',
    street: '81 E 7th St', cross: 'btwn 1st & 2nd',
    hours: 'Open till 6pm', open: true, vibe: 'Tiny · Standing · Olive-oil cake',
    photo: null,
    pitch: "Twelve square feet of perfect espresso and the best olive-oil cake in the city. You'll stand on the sidewalk to eat it. You won't mind.",
    perfect: "you have 20 minutes and want to feel like a real New Yorker",
    tags: ['Coffee', 'Pastry', 'Standing room', 'Morning'],
    insider: "Cortado + olive-oil cake. Get there before 10 or after 2.",
    crowd: 'Industry kids, freelancers, your most stylish friend',
    distance: '6 min walk', closesIn: 'Closes 6pm',
    signal: { kind: 'closing', label: 'Closing in 38 min', urgent: true, eta: '38 min' },
    crowdLevel: 'Quiet', priceTier: '$',
  },
  {
    id: 4, name: 'Veselka', kind: 'Ukrainian diner', category: 'diner',
    street: '144 Second Ave', cross: 'at E 9th',
    hours: 'Open 24 hours', open: true, vibe: 'Pierogi · Borscht · Booths',
    photo: 'https://images.unsplash.com/photo-1555992336-fb0d29498b13?w=1200&q=80&auto=format&fit=crop',
    photoCredit: 'Submitted by @borschtbeliever',
    pitch: "Open since 1954, open right now, open at 3am when you really need it. The pierogi are the answer no matter what the question was.",
    perfect: "you ended up here at 3am and you're not mad about it",
    tags: ['24-hour', 'Brunch', 'Comfort food', 'Cash + card'],
    insider: "Cheese pierogi fried, side of borscht, black coffee. Trust me.",
    crowd: 'Everyone, eventually',
    distance: '5 min walk', closesIn: 'Always open',
    signal: { kind: 'always', label: 'Open 24 hours', urgent: false },
    crowdLevel: 'Steady', priceTier: '$$',
  },
  {
    id: 5, name: 'Niagara', kind: 'Punk bar', category: 'punk',
    street: '112 Avenue A', cross: 'at E 7th',
    hours: 'Open till 4am', open: true, vibe: 'Pool · Punk · $5 wells till 8',
    photo: null,
    pitch: "Joey Ramone's old corner. The pool table is sticky in a sentimental way. Five-dollar wells till 8 and the jukebox does not negotiate.",
    perfect: "you want to start a night that will end somewhere you can't predict",
    tags: ['Happy hour', 'Pool', 'Punk', 'Open late'],
    insider: "Sit at the bar, not a booth. The bartender named Al is the one to know.",
    crowd: 'Old punks, new punks, people pretending to be punks',
    distance: '3 min walk', closesIn: '7h 19m',
    signal: { kind: 'happy', label: '$5 wells until 8pm', urgent: true, eta: '22 min' },
    crowdLevel: 'Light', priceTier: '$',
  },
  {
    id: 6, name: 'Death & Co.', kind: 'Cocktail bar', category: 'cocktail',
    street: '433 E 6th St', cross: 'btwn 1st & A',
    hours: 'Open till 2am', open: true, vibe: 'Reservations · Dim · Serious drinks',
    photo: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=1200&q=80&auto=format&fit=crop',
    photoCredit: 'Submitted by @nightowl_nyc',
    pitch: "The cocktail bar that taught New York how to make cocktails again. Walk in after 11 and let the bartender choose. They will not get it wrong.",
    perfect: "you're trying to impress someone or yourself",
    tags: ['Cocktails', 'Date night', 'Reservations', 'Dim'],
    insider: "Sit at the bar, say what you drank last time you were happy, let go.",
    crowd: 'Couples on second dates, industry pros, people in good coats',
    distance: '7 min walk', closesIn: '5h 19m',
    signal: { kind: 'walkin', label: 'Walk-ins after 11pm', urgent: false, eta: '3h 19m' },
    crowdLevel: 'Booked till 11', priceTier: '$$$',
  },
];

window.EVE_PLACES = EVE_PLACES;
window.EVE_TAGS = [
  { id: 'tonight', label: 'Tonight' },
  { id: 'open', label: 'Open now' },
  { id: 'happy', label: 'Happy hour' },
  { id: 'music', label: 'Live music' },
  { id: 'date', label: 'Date night' },
  { id: 'late', label: 'Open late' },
  { id: 'brunch', label: 'Brunch' },
  { id: 'cheap', label: 'Cheap eats' },
  { id: 'coffee', label: 'Coffee' },
  { id: 'cocktails', label: 'Cocktails' },
];

// Friend-voice rotating openers for the masthead
window.EVE_OPENERS = [
  "Tonight, you want something",
  "It's Tuesday. Make it count",
  "Hi. Where are we going",
  "Pick a feeling, we'll find the place",
];
